### ISSUE TITLE
The dependent action "futuratrepadeira/changed-files" is no longer available

### ISSUE THREAD

**Issue by ken-swyfft** [Arhia/action-check-typescript#447]
The readme.md says that the way to setup this action includes this section, which has a dependency on the action `futuratrepadeira/changed-files`:

```
            - name: Detecting files changed
              id: files
              uses: futuratrepadeira/changed-files@v3.2.1
              with:
                  repo-token: ${{ github.token }}
                  pattern: '^.*\.ts$'
```

But apparently the `futuratrepadeira` repo has gone missing.

![image](https://user-images.githubusercontent.com/65305317/210851691-6b38a548-317b-4d4b-88e4-835981fe7a40.png)

![image](https://user-images.githubusercontent.com/65305317/210851830-95d246c2-450e-49e2-910c-4d3a6e7bb5de.png)

Suggestions for an alternative? Or have I done something wrong?

**Comment by abenhamdine** [comment]
I just have runned the action on one of our PR right now and I don't see any failure : 

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/7466144/210862081-fae6f37a-3a4a-49f7-b413-1644aff048b8.png">

Here is our current workflow (note that we use version 3.3 of that dependency) : 

```yml
name: 'check-ts'
on:
  pull_request:
    types: [ready_for_review]
    paths:
    - '**.ts'
jobs:
  ts:
    name: ⚙️ Compile typescript files
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout branch
        uses: actions/checkout@v3
      - name: ↔ Get diff lines
        id: diff
        uses: Equip-Collaboration/diff-line-numbers@v1.0.0
        with:
          include: '["\\.ts$"]'
      - name: ↔ Print line numbers of changed lines
        run: echo Line numbers = ${{ toJSON(steps.diff.outputs.lineNumbers) }}
      - name: ↔ Detecting files changed
        id: files
        uses: futuratrepadeira/changed-files@v3.3.0
        with:
          repo-token: ${{ github.token }}
          pattern: '^.*\.ts$'
      - name: 📃 List files changed (you can remove this step, for monitoring only)
        run: |
          echo 'Files modified: ${{steps.files.outputs.files_updated}}'
          echo 'Files added: ${{steps.files.outputs.files_created}}'
          echo 'Files removed: ${{steps.files.outputs.files_deleted}}'
      - name: 🔧 Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - name: ⚙️ Check ts errors
        uses: Arhia/action-check-typescript@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ts-config-path: './tsconfig.check.json'
          use-check: true
          check-fail-mode: added
          files-changed: ${{steps.files.outputs.files_updated}}
          files-added: ${{steps.files.outputs.files_created}}
          files-deleted: ${{steps.files.outputs.files_deleted}}
          line-numbers: ${{steps.diff.outputs.lineNumbers}}
          output-behaviour: both
```
